apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: db
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: 471112916406.dkr.ecr.us-east-1.amazonaws.com/clo835-db:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: pass@1234
      ports:
        - containerPort: 3306
  imagePullSecrets:
    - name: regcred