apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  namespace: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: flask-app
          image: 471112916406.dkr.ecr.us-east-1.amazonaws.com/clo835-app:latest
          imagePullPolicy: Always
          env:
            - name: DBHOST
              value: mysql.db.svc.cluster.local
            - name: DBPORT
              value: "3306"
            - name: DBUSER
              value: root
            - name: DBPWD
              value: pass@1234
            - name: APP_COLOR
              value: blue
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
