#CLO835-Assignment1-senindumendis

name: Deploy to AWS ECR
on: 
  push:
    branches: [ master ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest
   
    steps:

    - name: Check out code
      uses: actions/checkout@v4

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: Build and push app tier image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY_APP: clo835-app
        ECR_REPOSITORY_DB: clo835-db
        IMAGE_TAG: v1.0
      run: |
        ls -al
        # Docker build Mysql
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_DB:$IMAGE_TAG -f db/Dockerfile .
        # Push Mysql to AWS ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_DB:$IMAGE_TAG

         # Docker build Python App
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_APP:$IMAGE_TAG .
        # Push Python App to AWS ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY_APP:$IMAGE_TAG